# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b919fe05b2703d8c1d72dcc1685f0c70d122e2315dd9f39f4c0b5bf2b2d6a7246d2c5b7072e79b76d1c0f3b3428b0532c63180b246702a0a37b197d8de3691

test:
  secret_key_base: 15fcaa2da11baefdb62a3d17566ff3d13fa2f37dbd4c1a4930b28dda13df17c1df8a52b8b90488c854991ac77a72a823ae7d59b6619ef67af797f46a91e16ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
